[package]
name = "snake_move"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.24.1"}
num-traits = "0.2.15"
serde = { version = "1.0", features = ["derive"], optional = true }
