[package]
name = "snake"
version = "0.1.0"
authors = ["lessball@hotmal.com <lessball@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
